export const items = [
  {
    name: 'Building',
    children: [
      {
        name: '0',
        image: 'assets/models/thumbnails_new/books.png',
        model: 'assets/models/gltf/books.glb',
        type: '0',
        format: 'gltf',
      },
      {
        name: '1',
        image:
          'assets/models/thumbnails/thumbnail_Church-Chair-oak-white_1024x1024.jpg',
        model: 'assets/models/js/gus-churchchair-whiteoak.js',
        type: '1',
      },
      {
        name: '2',
        image: 'assets/models/thumbnails/thumbnail_nyc2.jpg',
        model: 'assets/models/js/nyc-poster2.js',
        type: '2',
      },
      {
        name: '3',
        image: 'assets/models/thumbnails/thumbnail_window.png',
        model: 'assets/models/js/whitewindow.js',
        type: '3',
      },
      {
        name: '4',
        image: 'assets/models/thumbnails_new/ceilingFan.png',
        model: 'assets/models/gltf/ceilingFan.gltf',
        type: '4',
        format: 'gltf',
      },
      {
        name: '7',
        image:
          'assets/models/thumbnails/thumbnail_Screen_Shot_2014-10-27_at_8.04.12_PM.png',
        model: 'assets/models/js/closed-door28x80_baked.js',
        type: '7',
      },
      {
        name: '8',
        image: 'assets/models/thumbnails/thumbnail_cb-blue-block60x96.png',
        model: 'assets/models/js/cb-blue-block-60x96.js',
        type: '8',
      },
      {
        name: '9',
        image:
          'assets/models/thumbnails/thumbnail_clapboard-white-60-media-console-1.jpg',
        model: 'assets/models/js/cb-clapboard_baked.js',
        type: '9',
      },

      {
        name: 'Open Door',
        image:
          'assets/models/thumbnails/thumbnail_Screen_Shot_2014-10-27_at_8.22.46_PM.png',
        model: 'assets/models/js/open_door.js',
        type: '7',
      },
      {
        name: 'Red Chair',
        image: 'assets/models/thumbnails/thumbnail_tn-orange.png',
        model: 'assets/models/js/ik-ekero-orange_baked.js',
        type: '1',
      },
      {
        name: 'Blue Chair',
        image: 'assets/models/thumbnails/thumbnail_ekero-blue3.png',
        model: 'assets/models/js/ik-ekero-blue_baked.js',
        type: '1',
      },
      {
        name: 'Dresser - Dark Wood',
        image: 'assets/models/thumbnails/thumbnail_matera_dresser_5.png',
        model: 'assets/models/js/DWR_MATERA_DRESSER2.js',
        type: '1',
      },
      {
        name: 'Dresser - White',
        image: 'assets/models/thumbnails/thumbnail_img25o.jpg',
        model: 'assets/models/js/we-narrow6white_baked.js',
        type: '1',
      },
      {
        name: 'Bedside table - Shale',
        image:
          'assets/models/thumbnails/thumbnail_Blu-Dot-Shale-Bedside-Table.jpg',
        model: 'assets/models/js/bd-shalebedside-smoke_baked.js',
        type: '1',
      },
      {
        name: 'Bedside table - White',
        image:
          'assets/models/thumbnails/thumbnail_arch-white-oval-nightstand.jpg',
        model: 'assets/models/js/cb-archnight-white_baked.js',
        type: '1',
      },
      {
        name: 'Wardrobe - White',
        image: 'assets/models/thumbnails/thumbnail_TN-ikea-kvikine.png',
        model: 'assets/models/js/ik-kivine_baked.js',
        type: '1',
      },
      {
        name: 'Full Bed',
        image:
          'assets/models/thumbnails/thumbnail_nordli-bed-frame__0159270_PE315708_S4.JPG',
        model: 'assets/models/js/ik_nordli_full.js',
        type: '1',
      },
      {
        name: 'Bookshelf',
        image: 'assets/models/thumbnails/thumbnail_kendall-walnut-bookcase.jpg',
        model: 'assets/models/js/cb-kendallbookcasewalnut_baked.js',
        type: '1',
      },

      {
        name: 'Media Console - Black',
        image:
          'assets/models/thumbnails/thumbnail_moore-60-media-console-1.jpg',
        model: 'assets/models/js/cb-moore_baked.js',
        type: '9',
      },
      {
        name: 'Sectional - Olive',
        image: 'assets/models/thumbnails/thumbnail_img21o.jpg',
        model: 'assets/models/js/we-crosby2piece-greenbaked.js',
        type: '1',
      },
      {
        name: 'Sofa - Grey',
        image: 'assets/models/thumbnails/thumbnail_rochelle-sofa-3.jpg',
        model: 'assets/models/js/cb-rochelle-gray_baked.js',
        type: '1',
      },
      {
        name: 'Wooden Trunk',
        image: 'assets/models/thumbnails/thumbnail_teca-storage-trunk.jpg',
        model: 'assets/models/js/cb-tecs_baked.js',
        type: '1',
      },
      {
        name: 'Floor Lamp',
        image: 'assets/models/thumbnails/thumbnail_ore-white.png',
        model: 'assets/models/js/ore-3legged-white_baked.js',
        type: '1',
      },
      {
        name: 'Coffee Table - Wood',
        image:
          'assets/models/thumbnails/thumbnail_stockholm-coffee-table__0181245_PE332924_S4.JPG',
        model: 'assets/models/js/ik-stockholmcoffee-brown.js',
        type: '1',
      },
      {
        name: 'Side Table',
        image:
          'assets/models/thumbnails/thumbnail_Screen_Shot_2014-02-21_at_1.24.58_PM.png',
        model: 'assets/models/js/GUSossingtonendtable.js',
        type: '1',
      },
      {
        name: 'Dining Table',
        image: 'assets/models/thumbnails/thumbnail_scholar-dining-table.jpg',
        model: 'assets/models/js/cb-scholartable_baked.js',
        type: '1',
      },
      {
        name: 'Dining table',
        image:
          'assets/models/thumbnails/thumbnail_Screen_Shot_2014-01-28_at_6.49.33_PM.png',
        model: 'assets/models/js/BlakeAvenuejoshuatreecheftable.js',
        type: '1',
      },

      {
        name: 'Simple Cabinet',
        image: 'assets/models/thumbnails/thumbnail_cabinet.png',
        model: 'assets/models/js/cabinet.json',
        type: '1',
      },
    ],
  },
  {
    name: 'Sports Court',
    children: [
      {
        name: 'Sports Court1',
        children: [
          {
            name: 'Duck',
            image: 'assets/models/thumbnails/thumbnail_duck.png',
            model: 'assets/models/js/Duck.gltf',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Simplecabinet',
            image: 'assets/models/thumbnails_new/SimpleCabinet.png',
            model: 'assets/models/gltf/SimpleCabinet.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Bathroomcabinet',
            image: 'assets/models/thumbnails_new/bathroomCabinet.png',
            model: 'assets/models/gltf/bathroomCabinet.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Bathroomcabinetdrawer',
            image: 'assets/models/thumbnails_new/bathroomCabinetDrawer.png',
            model: 'assets/models/gltf/bathroomCabinetDrawer.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Bathroommirror',
            image: 'assets/models/thumbnails_new/bathroomMirror.png',
            model: 'assets/models/gltf/bathroomMirror.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Bathroomsink',
            image: 'assets/models/thumbnails_new/bathroomSink.png',
            model: 'assets/models/gltf/bathroomSink.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Bathroomsinksquare',
            image: 'assets/models/thumbnails_new/bathroomSinkSquare.png',
            model: 'assets/models/gltf/bathroomSinkSquare.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Bathtub',
            image: 'assets/models/thumbnails_new/bathtub.png',
            model: 'assets/models/gltf/bathtub.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Bear',
            image: 'assets/models/thumbnails_new/bear.png',
            model: 'assets/models/gltf/bear.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Bedbunk',
            image: 'assets/models/thumbnails_new/bedBunk.png',
            model: 'assets/models/gltf/bedBunk.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Beddouble',
            image: 'assets/models/thumbnails_new/bedDouble.png',
            model: 'assets/models/gltf/bedDouble.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Bedsingle',
            image: 'assets/models/thumbnails_new/bedSingle.png',
            model: 'assets/models/gltf/bedSingle.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Bench',
            image: 'assets/models/thumbnails_new/bench.png',
            model: 'assets/models/gltf/bench.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Benchcushion',
            image: 'assets/models/thumbnails_new/benchCushion.png',
            model: 'assets/models/gltf/benchCushion.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Benchcushionlow',
            image: 'assets/models/thumbnails_new/benchCushionLow.png',
            model: 'assets/models/gltf/benchCushionLow.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Bookcaseclosed',
            image: 'assets/models/thumbnails_new/bookcaseClosed.png',
            model: 'assets/models/gltf/bookcaseClosed.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Bookcasecloseddoors',
            image: 'assets/models/thumbnails_new/bookcaseClosedDoors.png',
            model: 'assets/models/gltf/bookcaseClosedDoors.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Bookcaseclosedwide',
            image: 'assets/models/thumbnails_new/bookcaseClosedWide.png',
            model: 'assets/models/gltf/bookcaseClosedWide.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Bookcaseopen',
            image: 'assets/models/thumbnails_new/bookcaseOpen.png',
            model: 'assets/models/gltf/bookcaseOpen.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Bookcaseopenlow',
            image: 'assets/models/thumbnails_new/bookcaseOpenLow.png',
            model: 'assets/models/gltf/bookcaseOpenLow.glb',
            type: '1',
            format: 'gltf',
          },

          {
            name: 'Cabinetbed',
            image: 'assets/models/thumbnails_new/cabinetBed.png',
            model: 'assets/models/gltf/cabinetBed.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Cabinetbeddrawer',
            image: 'assets/models/thumbnails_new/cabinetBedDrawer.png',
            model: 'assets/models/gltf/cabinetBedDrawer.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Cabinetbeddrawertable',
            image: 'assets/models/thumbnails_new/cabinetBedDrawerTable.png',
            model: 'assets/models/gltf/cabinetBedDrawerTable.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Cabinettelevision',
            image: 'assets/models/thumbnails_new/cabinetTelevision.png',
            model: 'assets/models/gltf/cabinetTelevision.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Cabinettelevisiondoors',
            image: 'assets/models/thumbnails_new/cabinetTelevisionDoors.png',
            model: 'assets/models/gltf/cabinetTelevisionDoors.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Cardboardboxclosed',
            image: 'assets/models/thumbnails_new/cardboardBoxClosed.png',
            model: 'assets/models/gltf/cardboardBoxClosed.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Cardboardboxopen',
            image: 'assets/models/thumbnails_new/cardboardBoxOpen.png',
            model: 'assets/models/gltf/cardboardBoxOpen.glb',
            type: '0',
            format: 'gltf',
          },

          {
            name: 'Chair',
            image: 'assets/models/thumbnails_new/chair.png',
            model: 'assets/models/gltf/chair.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Chaircushion',
            image: 'assets/models/thumbnails_new/chairCushion.png',
            model: 'assets/models/gltf/chairCushion.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Chairdesk',
            image: 'assets/models/thumbnails_new/chairDesk.png',
            model: 'assets/models/gltf/chairDesk.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Chairmoderncushion',
            image: 'assets/models/thumbnails_new/chairModernCushion.png',
            model: 'assets/models/gltf/chairModernCushion.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Chairmodernframecushion',
            image: 'assets/models/thumbnails_new/chairModernFrameCushion.png',
            model: 'assets/models/gltf/chairModernFrameCushion.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Chairrounded',
            image: 'assets/models/thumbnails_new/chairRounded.png',
            model: 'assets/models/gltf/chairRounded.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Chandelier',
            image: 'assets/models/thumbnails_new/nopreview.png',
            model: 'assets/models/gltf/chandelier.gltf',
            type: '4',
            format: 'gltf',
          },
          {
            name: 'Coatrack',
            image: 'assets/models/thumbnails_new/coatRack.png',
            model: 'assets/models/gltf/coatRack.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Coatrackstanding',
            image: 'assets/models/thumbnails_new/coatRackStanding.png',
            model: 'assets/models/gltf/coatRackStanding.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Computerkeyboard',
            image: 'assets/models/thumbnails_new/computerKeyboard.png',
            model: 'assets/models/gltf/computerKeyboard.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Computermouse',
            image: 'assets/models/thumbnails_new/computerMouse.png',
            model: 'assets/models/gltf/computerMouse.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Computerscreen',
            image: 'assets/models/thumbnails_new/computerScreen.png',
            model: 'assets/models/gltf/computerScreen.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Desk',
            image: 'assets/models/thumbnails_new/desk.png',
            model: 'assets/models/gltf/desk.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Deskcorner',
            image: 'assets/models/thumbnails_new/deskCorner.png',
            model: 'assets/models/gltf/deskCorner.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Doorway',
            image: 'assets/models/thumbnails_new/doorway.png',
            model: 'assets/models/gltf/doorway.glb',
            type: '3',
            format: 'gltf',
          },
          {
            name: 'Doorwayfront',
            image: 'assets/models/thumbnails_new/doorwayFront.png',
            model: 'assets/models/gltf/doorwayFront.glb',
            type: '3',
            format: 'gltf',
          },
          {
            name: 'Doorwayopen',
            image: 'assets/models/thumbnails_new/doorwayOpen.png',
            model: 'assets/models/gltf/doorwayOpen.glb',
            type: '3',
            format: 'gltf',
          },
          {
            name: 'Dryer',
            image: 'assets/models/thumbnails_new/dryer.png',
            model: 'assets/models/gltf/dryer.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Floorcorner',
            image: 'assets/models/thumbnails_new/floorCorner.png',
            model: 'assets/models/gltf/floorCorner.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Floorcornerround',
            image: 'assets/models/thumbnails_new/floorCornerRound.png',
            model: 'assets/models/gltf/floorCornerRound.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Floorfull',
            image: 'assets/models/thumbnails_new/floorFull.png',
            model: 'assets/models/gltf/floorFull.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Floorhalf',
            image: 'assets/models/thumbnails_new/floorHalf.png',
            model: 'assets/models/gltf/floorHalf.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Hoodlarge',
            image: 'assets/models/thumbnails_new/hoodLarge.png',
            model: 'assets/models/gltf/hoodLarge.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Hoodmodern',
            image: 'assets/models/thumbnails_new/hoodModern.png',
            model: 'assets/models/gltf/hoodModern.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Kitchenbar',
            image: 'assets/models/thumbnails_new/kitchenBar.png',
            model: 'assets/models/gltf/kitchenBar.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Kitchenbarend',
            image: 'assets/models/thumbnails_new/kitchenBarEnd.png',
            model: 'assets/models/gltf/kitchenBarEnd.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Kitchenblender',
            image: 'assets/models/thumbnails_new/kitchenBlender.png',
            model: 'assets/models/gltf/kitchenBlender.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinet',
            image: 'assets/models/thumbnails_new/kitchenCabinet.png',
            model: 'assets/models/gltf/kitchenCabinet.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinetcornerinner',
            image: 'assets/models/thumbnails_new/kitchenCabinetCornerInner.png',
            model: 'assets/models/gltf/kitchenCabinetCornerInner.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinetcornerround',
            image: 'assets/models/thumbnails_new/kitchenCabinetCornerRound.png',
            model: 'assets/models/gltf/kitchenCabinetCornerRound.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinetdrawer',
            image: 'assets/models/thumbnails_new/kitchenCabinetDrawer.png',
            model: 'assets/models/gltf/kitchenCabinetDrawer.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinetupper',
            image: 'assets/models/thumbnails_new/kitchenCabinetUpper.png',
            model: 'assets/models/gltf/kitchenCabinetUpper.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinetuppercorner',
            image: 'assets/models/thumbnails_new/kitchenCabinetUpperCorner.png',
            model: 'assets/models/gltf/kitchenCabinetUpperCorner.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinetupperdouble',
            image: 'assets/models/thumbnails_new/kitchenCabinetUpperDouble.png',
            model: 'assets/models/gltf/kitchenCabinetUpperDouble.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Kitchencabinetupperlow',
            image: 'assets/models/thumbnails_new/kitchenCabinetUpperLow.png',
            model: 'assets/models/gltf/kitchenCabinetUpperLow.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Kitchencoffeemachine',
            image: 'assets/models/thumbnails_new/kitchenCoffeeMachine.png',
            model: 'assets/models/gltf/kitchenCoffeeMachine.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Kitchenfridge',
            image: 'assets/models/thumbnails_new/kitchenFridge.png',
            model: 'assets/models/gltf/kitchenFridge.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Kitchenfridgebuiltin',
            image: 'assets/models/thumbnails_new/kitchenFridgeBuiltIn.png',
            model: 'assets/models/gltf/kitchenFridgeBuiltIn.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Kitchenfridgelarge',
            image: 'assets/models/thumbnails_new/kitchenFridgeLarge.png',
            model: 'assets/models/gltf/kitchenFridgeLarge.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Kitchenfridgesmall',
            image: 'assets/models/thumbnails_new/kitchenFridgeSmall.png',
            model: 'assets/models/gltf/kitchenFridgeSmall.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Kitchenmicrowave',
            image: 'assets/models/thumbnails_new/kitchenMicrowave.png',
            model: 'assets/models/gltf/kitchenMicrowave.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Kitchensink',
            image: 'assets/models/thumbnails_new/kitchenSink.png',
            model: 'assets/models/gltf/kitchenSink.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Kitchenstove',
            image: 'assets/models/thumbnails_new/kitchenStove.png',
            model: 'assets/models/gltf/kitchenStove.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Kitchenstoveelectric',
            image: 'assets/models/thumbnails_new/kitchenStoveElectric.png',
            model: 'assets/models/gltf/kitchenStoveElectric.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Lamproundfloor',
            image: 'assets/models/thumbnails_new/lampRoundFloor.png',
            model: 'assets/models/gltf/lampRoundFloor.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Lamproundtable',
            image: 'assets/models/thumbnails_new/lampRoundTable.png',
            model: 'assets/models/gltf/lampRoundTable.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Lampsquareceiling',
            image: 'assets/models/thumbnails_new/lampSquareCeiling.png',
            model: 'assets/models/gltf/lampSquareCeiling.glb',
            type: '4',
            format: 'gltf',
          },
          {
            name: 'Lampsquarefloor',
            image: 'assets/models/thumbnails_new/lampSquareFloor.png',
            model: 'assets/models/gltf/lampSquareFloor.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Lampsquaretable',
            image: 'assets/models/thumbnails_new/lampSquareTable.png',
            model: 'assets/models/gltf/lampSquareTable.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Lampwall',
            image: 'assets/models/thumbnails_new/lampWall.png',
            model: 'assets/models/gltf/lampWall.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Laptop',
            image: 'assets/models/thumbnails_new/laptop.png',
            model: 'assets/models/gltf/laptop.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Loungechair',
            image: 'assets/models/thumbnails_new/loungeChair.png',
            model: 'assets/models/gltf/loungeChair.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Loungechairrelax',
            image: 'assets/models/thumbnails_new/loungeChairRelax.png',
            model: 'assets/models/gltf/loungeChairRelax.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Loungedesignchair',
            image: 'assets/models/thumbnails_new/loungeDesignChair.png',
            model: 'assets/models/gltf/loungeDesignChair.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Loungedesignsofa',
            image: 'assets/models/thumbnails_new/loungeDesignSofa.png',
            model: 'assets/models/gltf/loungeDesignSofa.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Loungedesignsofacorner',
            image: 'assets/models/thumbnails_new/loungeDesignSofaCorner.png',
            model: 'assets/models/gltf/loungeDesignSofaCorner.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Loungesofa',
            image: 'assets/models/thumbnails_new/loungeSofa.png',
            model: 'assets/models/gltf/loungeSofa.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Loungesofacorner',
            image: 'assets/models/thumbnails_new/loungeSofaCorner.png',
            model: 'assets/models/gltf/loungeSofaCorner.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Loungesofalong',
            image: 'assets/models/thumbnails_new/loungeSofaLong.png',
            model: 'assets/models/gltf/loungeSofaLong.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Loungesofaottoman',
            image: 'assets/models/thumbnails_new/loungeSofaOttoman.png',
            model: 'assets/models/gltf/loungeSofaOttoman.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Paneling',
            image: 'assets/models/thumbnails_new/paneling.png',
            model: 'assets/models/gltf/paneling.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Pillow',
            image: 'assets/models/thumbnails_new/pillow.png',
            model: 'assets/models/gltf/pillow.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Pillowblue',
            image: 'assets/models/thumbnails_new/pillowBlue.png',
            model: 'assets/models/gltf/pillowBlue.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Pillowbluelong',
            image: 'assets/models/thumbnails_new/pillowBlueLong.png',
            model: 'assets/models/gltf/pillowBlueLong.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Pillowlong',
            image: 'assets/models/thumbnails_new/pillowLong.png',
            model: 'assets/models/gltf/pillowLong.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Plantsmall1',
            image: 'assets/models/thumbnails_new/plantSmall1.png',
            model: 'assets/models/gltf/plantSmall1.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Plantsmall2',
            image: 'assets/models/thumbnails_new/plantSmall2.png',
            model: 'assets/models/gltf/plantSmall2.glb',
            type: '1',
            format: 'gltf',
          },
        ],
      },
      {
        name: 'Sports Court2',
        children: [
          {
            name: 'Plantsmall3',
            image: 'assets/models/thumbnails_new/plantSmall3.png',
            model: 'assets/models/gltf/plantSmall3.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Pottedplant',
            image: 'assets/models/thumbnails_new/pottedPlant.png',
            model: 'assets/models/gltf/pottedPlant.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Radio',
            image: 'assets/models/thumbnails_new/radio.png',
            model: 'assets/models/gltf/radio.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Rugdoormat',
            image: 'assets/models/thumbnails_new/rugDoormat.png',
            model: 'assets/models/gltf/rugDoormat.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Rugrectangle',
            image: 'assets/models/thumbnails_new/rugRectangle.png',
            model: 'assets/models/gltf/rugRectangle.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Ruground',
            image: 'assets/models/thumbnails_new/rugRound.png',
            model: 'assets/models/gltf/rugRound.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Rugrounded',
            image: 'assets/models/thumbnails_new/rugRounded.png',
            model: 'assets/models/gltf/rugRounded.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Rugsquare',
            image: 'assets/models/thumbnails_new/rugSquare.png',
            model: 'assets/models/gltf/rugSquare.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Shower',
            image: 'assets/models/thumbnails_new/shower.png',
            model: 'assets/models/gltf/shower.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Showerround',
            image: 'assets/models/thumbnails_new/showerRound.png',
            model: 'assets/models/gltf/showerRound.glb',
            type: '9',
            format: 'gltf',
          },
          {
            name: 'Sidetable',
            image: 'assets/models/thumbnails_new/sideTable.png',
            model: 'assets/models/gltf/sideTable.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Sidetabledrawers',
            image: 'assets/models/thumbnails_new/sideTableDrawers.png',
            model: 'assets/models/gltf/sideTableDrawers.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Speaker',
            image: 'assets/models/thumbnails_new/speaker.png',
            model: 'assets/models/gltf/speaker.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Speakersmall',
            image: 'assets/models/thumbnails_new/speakerSmall.png',
            model: 'assets/models/gltf/speakerSmall.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Stairs',
            image: 'assets/models/thumbnails_new/stairs.png',
            model: 'assets/models/gltf/stairs.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Stairscorner',
            image: 'assets/models/thumbnails_new/stairsCorner.png',
            model: 'assets/models/gltf/stairsCorner.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Stairsopen',
            image: 'assets/models/thumbnails_new/stairsOpen.png',
            model: 'assets/models/gltf/stairsOpen.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Stairsopensingle',
            image: 'assets/models/thumbnails_new/stairsOpenSingle.png',
            model: 'assets/models/gltf/stairsOpenSingle.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Stoolbar',
            image: 'assets/models/thumbnails_new/stoolBar.png',
            model: 'assets/models/gltf/stoolBar.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Stoolbarsquare',
            image: 'assets/models/thumbnails_new/stoolBarSquare.png',
            model: 'assets/models/gltf/stoolBarSquare.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Table',
            image: 'assets/models/thumbnails_new/table.png',
            model: 'assets/models/gltf/table.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tablecloth',
            image: 'assets/models/thumbnails_new/tableCloth.png',
            model: 'assets/models/gltf/tableCloth.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tablecoffee',
            image: 'assets/models/thumbnails_new/tableCoffee.png',
            model: 'assets/models/gltf/tableCoffee.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tablecoffeeglass',
            image: 'assets/models/thumbnails_new/tableCoffeeGlass.png',
            model: 'assets/models/gltf/tableCoffeeGlass.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tablecoffeeglasssquare',
            image: 'assets/models/thumbnails_new/tableCoffeeGlassSquare.png',
            model: 'assets/models/gltf/tableCoffeeGlassSquare.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tablecoffeesquare',
            image: 'assets/models/thumbnails_new/tableCoffeeSquare.png',
            model: 'assets/models/gltf/tableCoffeeSquare.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tablecross',
            image: 'assets/models/thumbnails_new/tableCross.png',
            model: 'assets/models/gltf/tableCross.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tablecrosscloth',
            image: 'assets/models/thumbnails_new/tableCrossCloth.png',
            model: 'assets/models/gltf/tableCrossCloth.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tableglass',
            image: 'assets/models/thumbnails_new/tableGlass.png',
            model: 'assets/models/gltf/tableGlass.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Tableround',
            image: 'assets/models/thumbnails_new/tableRound.png',
            model: 'assets/models/gltf/tableRound.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Televisionantenna',
            image: 'assets/models/thumbnails_new/televisionAntenna.png',
            model: 'assets/models/gltf/televisionAntenna.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Televisionmodern',
            image: 'assets/models/thumbnails_new/televisionModern.png',
            model: 'assets/models/gltf/televisionModern.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Televisionvintage',
            image: 'assets/models/thumbnails_new/televisionVintage.png',
            model: 'assets/models/gltf/televisionVintage.glb',
            type: '2',
            format: 'gltf',
          },
          {
            name: 'Toaster',
            image: 'assets/models/thumbnails_new/toaster.png',
            model: 'assets/models/gltf/toaster.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Toilet',
            image: 'assets/models/thumbnails_new/toilet.png',
            model: 'assets/models/gltf/toilet.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Toiletsquare',
            image: 'assets/models/thumbnails_new/toiletSquare.png',
            model: 'assets/models/gltf/toiletSquare.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Trashcan',
            image: 'assets/models/thumbnails_new/trashcan.png',
            model: 'assets/models/gltf/trashcan.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Wall',
            image: 'assets/models/thumbnails_new/wall.png',
            model: 'assets/models/gltf/wall.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Wallcorner',
            image: 'assets/models/thumbnails_new/wallCorner.png',
            model: 'assets/models/gltf/wallCorner.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Wallcornerrond',
            image: 'assets/models/thumbnails_new/wallCornerRond.png',
            model: 'assets/models/gltf/wallCornerRond.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Walldoorway',
            image: 'assets/models/thumbnails_new/wallDoorway.png',
            model: 'assets/models/gltf/wallDoorway.glb',
            type: '3',
            format: 'gltf',
          },
          {
            name: 'Walldoorwaywide',
            image: 'assets/models/thumbnails_new/wallDoorwayWide.png',
            model: 'assets/models/gltf/wallDoorwayWide.glb',
            type: '3',
            format: 'gltf',
          },
          {
            name: 'Wallhalf',
            image: 'assets/models/thumbnails_new/wallHalf.png',
            model: 'assets/models/gltf/wallHalf.glb',
            type: '0',
            format: 'gltf',
          },
          {
            name: 'Wallwindow',
            image: 'assets/models/thumbnails_new/wallWindow.png',
            model: 'assets/models/gltf/wallWindow.glb',
            type: '3',
            format: 'gltf',
          },
          {
            name: 'Wallwindowslide',
            image: 'assets/models/thumbnails_new/wallWindowSlide.png',
            model: 'assets/models/gltf/wallWindowSlide.glb',
            type: '3',
            format: 'gltf',
          },
          {
            name: 'Washer',
            image: 'assets/models/thumbnails_new/washer.png',
            model: 'assets/models/gltf/washer.glb',
            type: '1',
            format: 'gltf',
          },
          {
            name: 'Washerdryerstacked',
            image: 'assets/models/thumbnails_new/washerDryerStacked.png',
            model: 'assets/models/gltf/washerDryerStacked.glb',
            type: '1',
            format: 'gltf',
          },
        ],
      },
    ],
  },
];

// export const rectHome = `
// {
//   "floorplan": {
//       "corners": {
//           "71d4f128-ae80-3d58-9bd2-711c6ce6cdf2": {
//               "x": 0,
//               "y": 0,
//               "elevation": 4
//           },
//           "f90da5e3-9e0e-eba7-173d-eb0b071e838e": {
//               "x": 0,
//               "y": 5,
//               "elevation": 4
//           },
//           "da026c08-d76a-a944-8e7b-096b752da9ed": {
//               "x": 5,
//               "y": 5,
//               "elevation": 4
//           },
//           "4e3d65cb-54c0-0681-28bf-bddcc7bdb571": {
//               "x": 5,
//               "y": 0,
//               "elevation": 4
//           }
//       },
//       "walls": [{
//           "corner1": "71d4f128-ae80-3d58-9bd2-711c6ce6cdf2",
//           "corner2": "f90da5e3-9e0e-eba7-173d-eb0b071e838e",
//           "frontTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           },
//           "backTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           }
//       }, {
//           "corner1": "f90da5e3-9e0e-eba7-173d-eb0b071e838e",
//           "corner2": "da026c08-d76a-a944-8e7b-096b752da9ed",
//           "frontTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           },
//           "backTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           }
//       }, {
//           "corner1": "da026c08-d76a-a944-8e7b-096b752da9ed",
//           "corner2": "4e3d65cb-54c0-0681-28bf-bddcc7bdb571",
//           "frontTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           },
//           "backTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           }
//       }, {
//           "corner1": "4e3d65cb-54c0-0681-28bf-bddcc7bdb571",
//           "corner2": "71d4f128-ae80-3d58-9bd2-711c6ce6cdf2",
//           "frontTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           },
//           "backTexture": {
//               "url": "/assets/rooms/textures/wallmap.png",
//               "stretch": true,
//               "scale": 0
//           }
//       }],
//       "rooms": {
//           "71d4f128-ae80-3d58-9bd2-711c6ce6cdf2,4e3d65cb-54c0-0681-28bf-bddcc7bdb571,da026c08-d76a-a944-8e7b-096b752da9ed,f90da5e3-9e0e-eba7-173d-eb0b071e838e": {
//               "name": "A New Room"
//           }
//       },
//       "wallTextures": [],
//       "floorTextures": {},
//       "newFloorTextures": {},
//       "carbonSheet": {
//           "url": "",
//           "transparency": 1,
//           "x": 0,
//           "y": 0,
//           "anchorX": 0,
//           "anchorY": 0,
//           "width": 0.01,
//           "height": 0.01
//       }
//   },
//   "items": []
// }
// `;

export const rectHome = JSON.stringify({
  floorplan: {
    version: '0.0.2a',
    corners: {
      '71d4f128-ae80-3d58-9bd2-711c6ce6cdf2': { x: 0, y: 0, elevation: 4 },
      'f90da5e3-9e0e-eba7-173d-eb0b071e838e': { x: 0, y: 5, elevation: 4 },
      'da026c08-d76a-a944-8e7b-096b752da9ed': { x: 5, y: 5, elevation: 4 },
      '4e3d65cb-54c0-0681-28bf-bddcc7bdb571': { x: 5, y: 0, elevation: 4 },
    },
    walls: [
      {
        corner1: '71d4f128-ae80-3d58-9bd2-711c6ce6cdf2',
        corner2: 'f90da5e3-9e0e-eba7-173d-eb0b071e838e',
        frontTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        backTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        wallType: 'STRAIGHT',
        a: { x: -176.77669529663686, y: 176.7766952966369 },
        b: { x: -176.7766952966369, y: 323.22330470336317 },
      },
      {
        corner1: 'f90da5e3-9e0e-eba7-173d-eb0b071e838e',
        corner2: 'da026c08-d76a-a944-8e7b-096b752da9ed',
        frontTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        backTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        wallType: 'STRAIGHT',
        a: { x: 176.7766952966369, y: 676.7766952966368 },
        b: { x: 323.22330470336317, y: 676.776695296637 },
      },
      {
        corner1: 'da026c08-d76a-a944-8e7b-096b752da9ed',
        corner2: '4e3d65cb-54c0-0681-28bf-bddcc7bdb571',
        frontTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        backTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        wallType: 'STRAIGHT',
        a: { x: 676.7766952966368, y: 323.2233047033631 },
        b: { x: 676.776695296637, y: 176.77669529663686 },
      },
      {
        corner1: '4e3d65cb-54c0-0681-28bf-bddcc7bdb571',
        corner2: '71d4f128-ae80-3d58-9bd2-711c6ce6cdf2',
        frontTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        backTexture: {
          url: '/assets/rooms/textures/wallmap.png',
          stretch: true,
          scale: 0,
        },
        wallType: 'STRAIGHT',
        a: { x: 323.2233047033631, y: -176.77669529663686 },
        b: { x: 176.77669529663686, y: -176.7766952966369 },
      },
    ],
    rooms: {
      '71d4f128-ae80-3d58-9bd2-711c6ce6cdf2,4e3d65cb-54c0-0681-28bf-bddcc7bdb571,da026c08-d76a-a944-8e7b-096b752da9ed,f90da5e3-9e0e-eba7-173d-eb0b071e838e':
        { name: 'Mine' },
    },
    wallTextures: [],
    floorTextures: {},
    newFloorTextures: {},
    carbonSheet: {
      url: '',
      transparency: 1,
      x: 0,
      y: 0,
      anchorX: 0,
      anchorY: 0,
      width: 0.01,
      height: 0.01,
    },
  },
  items: [
    {
      item_name: '3',
      item_type: '3',
      model_url: 'assets/models/js/whitewindow.js',
      xPos: 147.71110311399423,
      yPos: 197.39903662054166,
      zPos: 0.4999999999999991,
      rotation: -1.812609019796174e-18,
      scale_x: 1,
      scale_y: 1,
      scale_z: 1,
      fixed: false,
      material_colors: [
        '#ffffff',
        '#a09050',
        '#a09050',
        '#ffffff',
        '#ffffff',
        '#6c6c6c',
        '#000000',
        '#000000',
        '#ffffff',
        '#ffffff',
        '#6c6c6c',
        '#ffffff',
      ],
    },
    {
      item_name: '9',
      item_type: '9',
      model_url: 'assets/models/js/cb-clapboard_baked.js',
      xPos: 340.18815523448933,
      yPos: 67.89999754396,
      zPos: 30.4,
      rotation: -1.812609019796174e-18,
      scale_x: 1,
      scale_y: 1,
      scale_z: 1,
      fixed: false,
      material_colors: ['#ffffff'],
    },
    {
      item_name: 'Bedside table - Shale',
      item_type: '1',
      model_url: 'assets/models/js/bd-shalebedside-smoke_baked.js',
      xPos: 218.20764719172064,
      yPos: 26.155249745364998,
      zPos: 176.77149898378866,
      rotation: 1.1787969372688563,
      scale_x: 1,
      scale_y: 1,
      scale_z: 1,
      fixed: false,
      material_colors: ['#ffffff'],
    },
  ],
});
